exp_name=rlvr_code_view_tool_sft
    python mason.py \
        --cluster ai2/jupiter-cirrascale-2 \
        --image saurabhs/open-coding-agent \
        --workspace ai2/open-coding-agent \
        --priority high \
        --preemptible \
        --num_nodes 4 \
        --gs_model_name saurabhs/ethans-Qwen3-8B-axolotl-thinkplain-e7 \
        --description "rlvr code view tool sft" \
        --max_retries 0 \
        --env VLLM_ALLOW_LONG_MAX_MODEL_LEN=1 \
        --env VLLM_DISABLE_COMPILE_CACHE=1 \
        --budget ai2/oe-adapt \
        --gpus 8 -- source configs/beaker_configs/ray_node_setup.sh \&\& source configs/beaker_configs/code_api_setup.sh \&\& python open_instruct/grpo_fast.py \
        --exp_name ${exp_name} \
        --beta 0.0 \
        --num_samples_per_prompt_rollout 16 \
        --num_unique_prompts_rollout 256 \
        --num_mini_batches 1 \
        --num_epochs 1 \
        --learning_rate 5e-7 \
        --per_device_train_batch_size 1 \
        --output_dir /output \
        --kl_estimator kl3 \
        --dataset_mixer_list saurabh5/rlvr-code-view-tool 1.0 \
        --dataset_mixer_list_splits train \
        --dataset_mixer_eval_list saurabh5/rlvr-code-view-tool 16 \
        --dataset_mixer_eval_list_splits train \
        --max_token_length 16384 \
        --max_prompt_token_length 16384 \
        --response_length 16384 \
        --pack_length 32768 \
        --model_name_or_path /weka/oe-adapt-default/ethans/llm-weights/Qwen3-8B-axolotl-thinkplain-e7 \
        --chat_template_name chatml \
        --non_stop_penalty False \
        --temperature 1.0 \
        --ground_truths_key ground_truth \
        --sft_messages_key messages \
        --total_episodes 10000000 \
        --deepspeed_stage 3 \
        --num_learners_per_node 8 8 \
        --vllm_num_engines 16 \
        --vllm_tensor_parallel_size 1 \
        --lr_scheduler_type constant \
        --apply_verifiable_reward true \
        --code_api_url \$CODE_API_URL/test_program \
        --code_view_api_endpoint \$CODE_API_URL/view_file \
        --seed 42 \
        --num_evals 5 \
        --save_freq 50 \
        --try_launch_beaker_eval_jobs_on_weka False \
        --gradient_checkpointing \
        --with_tracking \
        --oe_eval_max_length 16384 \
        --tools code_view \
        --max_tool_calls 15 \