python mason.py \
    --cluster ai2/augusta-google-1 \
    --workspace ai2/scaling-rl \
    --priority high \
    --image valpy/open_instruct_dev_with_rm --pure_docker_mode \
    --preemptible \
    --num_nodes 4 \
    --budget ai2/oe-adapt \
    --gpus 8 -- source configs/beaker_configs/ray_node_setup.sh \&\& python open_instruct/grpo_vllm_thread_ray_gtrl.py \
    --exp_name valpy_if_multi_tulu3.1_8b_grpo_with_rm_fixed \
    --beta 0.01 \
    --local_mini_batch_size 16 \
    --number_samples_per_prompt 8 \
    --local_rollout_batch_size 2 \
    --kl_estimator kl3 \
    --learning_rate 5e-7 \
    --dataset_mixer_list valpy/tulu3-sft-if-new-multi 1.0 \
    --dataset_mixer_list_splits train \
    --dataset_mixer_eval_list valpy/tulu3-sft-if-new-multi 16 \
    --dataset_mixer_eval_list_splits train \
    --max_token_length 2048 \
    --max_prompt_token_length 2048 \
    --response_length 2048 \
    --model_name_or_path allenai/Llama-3.1-Tulu-3-8B-DPO \
    --non_stop_penalty \
    --stop_token eos \
    --temperature 1.0 \
    --chat_template_name tulu \
    --total_episodes 2000000 \
    --penalty_reward_value 0.0 \
    --deepspeed_stage 2 \
    --per_device_train_batch_size 2 \
    --local_rollout_forward_batch_size 2 \
    --actor_num_gpus_per_node 4 8 \
    --num_epochs 1 \
    --vllm_tensor_parallel_size 1 \
    --vllm_num_engines 4 \
    --lr_scheduler_type constant \
    --apply_verifiable_reward true \
    --seed 1 \
    --num_evals 100 \
    --save_freq 100 \
    --reward_model_multiplier 1.0 \
    --reward_model_path allenai/Llama-3.1-Tulu-3-8B-RM \
    --no_try_launch_beaker_eval_jobs \
    --try_launch_beaker_eval_jobs_on_weka \
    --gradient_checkpointing \
    --with_tracking