model_name_or_path: allenai/OLMo-1.7-7B-hf
model_revision: main
use_flash_attn: true
tokenizer_name: allenai/OLMo-1.7-7B-hf
use_slow_tokenizer: false # olmo models only use fast tokenizers
dataset_name: /net/nfs.cirrascale/mosaic/liweij/auto_jailbreak/data/safety_training_data/v3/mixtures/tulu2mix-all-vani_b-50000-vani_h-50000-adv_b-50000-adv_h-50000.jsonl
max_seq_length: 2048
preprocessing_num_workers: 128
per_device_train_batch_size: 1 # note, this is set up for 8 GPUs
gradient_accumulation_steps: 16
learning_rate: 2.0e-06
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 3
output_dir: output/olmo_17_safe_sft/
with_tracking: true
report_to:
  - wandb
logging_steps: 1
checkpointing_steps: epoch
add_bos: true
