# Note, the exact model was trained on TPUs in a different repo
# Example file for mixing, use exact tulu 2 mixture for replication allenai/tulu-v2-sft-mixture
model_name_or_path: allenai/OLMoE-1B-7B-0824
model_revision: step1200000-tokens5033B
use_flash_attn: true
tokenizer_name: allenai/OLMoE-1B-7B-0824
use_slow_tokenizer: true
dataset_mixer:
  allenai/tulu-v3-mix-preview-4096-OLMoE: 1.0
  ai2-adapt-dev/daring-anteater-specialized: 1.0
max_seq_length: 4096 # Note, reduced from 8192 to fit on one GPU with DeepSpeed Stage3
preprocessing_num_workers: 128
per_device_train_batch_size: 2 # note, this is set up for 8 GPUs
gradient_accumulation_steps: 1 # effective batch size 128 for tulu 2
learning_rate: 2.0e-05
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 2
output_dir: /output/
with_tracking: true
report_to:
  - wandb
logging_steps: 1
checkpointing_steps: epoch
add_bos: true
