model_name_or_path: meta-llama/Meta-Llama-3-8B
model_revision: main
use_flash_attn: true
tokenizer_name: meta-llama/Meta-Llama-3-8B
use_slow_tokenizer: true
dataset_mixer:
    # Tulu V2 datasets
    allenai/tulu-v2-sft-mixture: 326154
    # Tulu V3 datasets (WIP)
    HuggingFaceH4/no_robots: 9500 # all
    ai2-adapt-dev/metamath-qa-reformat: 100000
    ai2-adapt-dev/codefeedback-single-turn-reformat: 156526 # all
    ai2-adapt-dev/daring-anteater-specialized: 17082
max_seq_length: 4096 # Note, reduced from 8192 to fit on one GPU with DeepSpeed Stage3
preprocessing_num_workers: 128
per_device_train_batch_size: 1 # note, this is set up for 8 GPUs
gradient_accumulation_steps: 4 # effective batch size 128 with 4 nodes
learning_rate: 5.0e-06 # best LR so far
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 2
output_dir: /output/
with_tracking: true
report_to:
  - wandb
logging_steps: 1
checkpointing_steps: epoch
dataset_mix_dir: /output/
checkpointing_steps: 1000
keep_last_n_checkpoints: 1
