python mason.py \
    --cluster ai2/augusta-google-1 \
    --workspace ai2/olmo-instruct \
    --priority high \
    --image jacobm/open-instruct-random-rewards --pure_docker_mode \
    --preemptible \
    --num_nodes 1 \
    --budget ai2/oe-adapt \
    --no_auto_dataset_cache \
    --gpus 8 -- source configs/beaker_configs/ray_node_setup.sh \&\& python open_instruct/grpo_fast.py \
    --exp_name qwen2p5_7b_random_rewards \
    --beta 0.01 \
    --num_unique_prompts_rollout 64 \
    --num_samples_per_prompt_rollout 16 \
    --try_launch_beaker_eval_jobs_on_weka \
    --kl_estimator kl3 \
    --learning_rate 5e-7 \
    --dataset_mixer_list allenai/RLVR-GSM-MATH-IF-Mixed-Constraints 1.0 \
    --dataset_mixer_list_splits train \
    --dataset_mixer_eval_list allenai/RLVR-GSM-MATH-IF-Mixed-Constraints 16 \
    --dataset_mixer_eval_list_splits train \
    --max_token_length 2048 \
    --max_prompt_token_length 2048 \
    --response_length 2048 \
    --pack_length 4096 \
    --model_name_or_path Qwen/Qwen2.5-7B \
    --apply_verifiable_reward false \
    --non_stop_penalty false \
    --non_stop_penalty_value 0.0 \
    --apply_random_rewards true \
    --random_reward 1.0 \
    --disable_reward_normalization true \
    --temperature 1.0 \
    --chat_template_name tulu \
    --total_episodes 2000000 \
    --deepspeed_stage 2 \
    --per_device_train_batch_size 1 \
    --num_mini_batches 2 \
    --num_learners_per_node 6 \
    --num_epochs 1 \
    --vllm_tensor_parallel_size 1 \
    --vllm_num_engines 2 \
    --lr_scheduler_type constant \
    --apply_verifiable_reward false \
    --seed 1 \
    --num_evals 1000 \
    --save_freq 50 \
    --gradient_checkpointing \
    --gather_whole_model False \
    --with_tracking
    --output_dir /weka/oe-adapt-default/jacobm/random-rewards/checkpoints/qwen2p5_7b_random_rewards \