python mason.py \
    --cluster ai2/augusta-google-1 \
    --workspace ai2/scaling-rl \
    --priority high \
    --image nathanl/open_instruct_auto --pure_docker_mode \
    --preemptible \
    --num_nodes 4 \
    --budget ai2/oe-adapt \
    --gpus 8 -- accelerate launch \
    --mixed_precision bf16 \
    --num_processes 8 \
    --use_deepspeed \
    --deepspeed_config_file configs/ds_configs/stage3_no_offloading_accelerate.conf \
    --deepspeed_multinode_launcher standard \
    open_instruct/dpo_tune_cache.py \
    --exp_name tulu3_8b_after_dpo_if_pref_strict \
    --model_name_or_path allenai/Llama-3.1-Tulu-3-8B-DPO \
    --model_revision main \
    --tokenizer_name allenai/Llama-3.1-Tulu-3-8B-DPO \
    --tokenizer_revision main \
    --use_slow_tokenizer \
    --dataset_mixer_list valpy/IF_preference_data_strict 1.0 \
    --max_seq_length 2048 \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --learning_rate 5e-07 \
    --lr_scheduler_type linear \
    --warmup_ratio 0.1 \
    --weight_decay 0.0 \
    --num_train_epochs 1 \
    --dpo_loss_type dpo_norm \
    --dpo_beta 5 \
    --use_flash_attn \
    --gradient_checkpointing \
    --report_to wandb \
    --with_tracking \
    --logging_steps 1 \
    --seed 8