model_name_or_path: Qwen/Qwen2.5-7B
model_revision: main
use_flash_attn: true
tokenizer_name: Qwen/Qwen2.5-7B
use_slow_tokenizer: true
dataset_mixer:
  ai2-adapt-dev/gtu-xlam-orig: 1.0
preprocessing_num_workers: 128
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 5.0e-06
chat_template_name: toolu
max_seq_length: 4096
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 2
output_dir: output/sft_8b
with_tracking: true
report_to:
  - wandb
logging_steps: 1
checkpointing_steps: epoch
dataset_mix_dir: output/sft_8b
