model_name_or_path: allenai/Llama-3.1-Tulu-3-70B-SFT
tokenizer_name: allenai/Llama-3.1-Tulu-3-70B-SFT
model_revision: main
use_flash_attn: true
gradient_checkpointing: true
dataset_mixer:
    allenai/llama-3.1-tulu-3-70b-preference-mixture: 1.0
use_slow_tokenizer: true
max_seq_length: 2048
preprocessing_num_workers: 16
per_device_train_batch_size: 1
gradient_accumulation_steps: 2 # designed for 8 GPUs, so batch size 128
learning_rate: 2.0e-7
lr_scheduler_type: linear
warmup_ratio: 0.1
weight_decay: 0.0
num_train_epochs: 1
output_dir: output/dpo_8b
with_tracking: true
report_to:
  - wandb
logging_steps: 1
use_lora: false
dpo_loss_type: dpo_norm
dpo_beta: 5
checkpointing_steps: epoch