# copied from internal repo https://github.com/allenai/docker-images
name: Push image to Beaker
description: Push image to Beaker images.
inputs:
  image:
    description: The tag of the built image
    required: true
  beaker:
    description: Upload release images to Beaker under this name
    required: false
    default: ""
  latest:
    description: If the image should also be pushed as latest
    required: false
    default: false
runs:
  using: composite
  # note, name used for this is associated with the beaker key in repo secrets
  steps:
    - shell: bash
      if: inputs.beaker != '' # previously startsWith(github.ref, 'refs/tags/') && ...
      run: |
        beaker_user=$(beaker account whoami --format json | jq -r '.[0].name')
        # Push release to Beaker.
        SHORT_SHA=$(git rev-parse --short HEAD)
        DESCRIPTION="Created from commit: ${SHORT_SHA}"
        beaker image create \
               --name "${{ inputs.beaker }}-${SHORT_SHA}-${{ github.run_id }}" ${{ inputs.image }} \
               --description "$DESCRIPTION"
        # We can't delete the old image because it might be used by a running job. Instead, we rename it to an empty 
        # string, so it will not be resolved by the Beaker client.
        echo "Deleting image $beaker_user/${{ inputs.beaker }}."
        beaker image rename $beaker_user/${{ inputs.beaker }} "" || true
        echo "Creating image $beaker_user/inputs.beaker."
        beaker image create \
               --name ${{ inputs.beaker }} ${{ inputs.image }} \
               --description "$DESCRIPTION"
