export mixin_it_up="hamishivi/math_rlvr_mixture_dpo 1.0 hamishivi/code_rlvr_mixture_dpo 1.0 hamishivi/IF_multi_constraints_upto5_filtered_dpo_0625_filter 30186 hamishivi/rlvr_general_mix 21387"

export exp_name=olmo3_fun_tool_run_${RANDOM}

python mason.py \
    --budget ai2/oe-adapt \
    --cluster ai2/augusta \
    --image hamishivi/open_instruct_tool_fun2 \
    --pure_docker_mode \
    --gs_model_name sm0922-rsn-dpo-delta-yolo_scottmix1_150k-8e-8__42__1758585338_olmo3 \
    --workspace ai2/olmo-instruct \
    --priority urgent \
    --preemptible \
    --num_nodes 4 \
    --gpus 8 \
    --max_retries 0 \
    --env RAY_CGRAPH_get_timeout=300 \
    --env VLLM_ALLOW_LONG_MAX_MODEL_LEN=1 \
    --env HOSTED_VLLM_API_BASE=http://saturn-cs-aus-240.reviz.ai2.in:8001/v1 \
    --secret SERPER_API_KEY=hamishivi_SERPER_API_KEY \
    --secret CRAWL4AI_API_KEY=hamishivi_CRAWL4AI_API_KEY \
    --env CRAWL4AI_API_URL=http://w046sy3a7g.execute-api.us-east-1.amazonaws.com/prod \
    -- source configs/beaker_configs/ray_node_setup.sh \&\& source configs/beaker_configs/code_api_setup.sh \&\& python open_instruct/grpo_fast.py \
        --exp_name ${exp_name} \
        --beta 0.0 \
        --num_samples_per_prompt_rollout 8 \
        --num_unique_prompts_rollout 64 \
        --num_mini_batches 1 \
        --num_epochs 1 \
        --learning_rate 1e-6 \
        --per_device_train_batch_size 1 \
        --output_dir /output \
        --kl_estimator kl3 \
        --dataset_mixer_list ${mixin_it_up} \
        --dataset_mixer_list_splits train \
        --dataset_mixer_eval_list hamishivi/omega-combined 8 allenai/IF_multi_constraints_upto5 8 saurabh5/rlvr_acecoder_filtered 8 hamishivi/tulu_3_rewritten_400k_string_f1_only_v2_nocode_all_filtered_qwen2_5_openthoughts2 4 hamishivi/virtuoussy_multi_subject_rlvr 4 \
        --dataset_mixer_eval_list_splits train \
        --max_prompt_token_length 2048 \
        --response_length 32768 \
        --pack_length 35840 \
        --model_name_or_path /weka/oe-adapt-default/hamishi/model_checkpoints/sm0922-rsn-dpo-delta-yolo_scottmix1_150k-8e-8__42__1758585338_olmo3 \
        --chat_template_name olmo_thinker \
        --non_stop_penalty False \
        --mask_truncated_completions False \
        --temperature 1.0 \
        --ground_truths_key ground_truth \
        --sft_messages_key messages \
        --total_episodes 10000000 \
        --deepspeed_stage 3 \
        --num_learners_per_node 8 8 \
        --vllm_num_engines 16 \
        --vllm_tensor_parallel_size 1 \
        --lr_scheduler_type constant \
        --apply_verifiable_reward true \
        --seed 1 \
        --local_eval_every 50 \
        --save_freq 50 \
        --try_launch_beaker_eval_jobs_on_weka False \
        --gradient_checkpointing \
        --with_tracking \
        --llm_judge_model hosted_vllm/Qwen/Qwen3-32B \
        --llm_judge_timeout 600 \
        --llm_judge_max_tokens 2048 \
        --llm_judge_max_context_length 32768 \
        --clip_higher 0.272 \
        --use_fp8_kv_cache False \
        --code_api_url https://p9f1719l7f.execute-api.us-west-2.amazonaws.com/prod/test_program \
        --code_pass_rate_reward_threshold 0.99 \
        --oe_eval_max_length 32768 \
        --checkpoint_state_freq 10000 \
        --backend_timeout 1200 \
        --inflight_updates true \
        --async_steps 8 \
        --advantage_normalization_type centered \
        --truncated_importance_sampling_ratio_cap 2.0 \
        --only_reward_good_outputs true \
        --max_tool_calls 10 \
        --system_prompt_override_file open_instruct/tools/system_prompts/olmo3_serper_crawl_python_prompt.txt \
        --tools search_serper browse_crawl4ai code \
        --code_tool_api_endpoint https://open-instruct-tool-server-10554368204.us-central1.run.app/execute