#!/usr/bin/env python3
import os


def generate_registries_conf():
    mirror_urls = os.environ.get("MIRROR_URL", "")

    if not mirror_urls:
        print("No MIRROR_URL environment variable set")
        return

    mirrors = [url.strip() for url in mirror_urls.split(",") if url.strip()]

    config = """[[registry]]
location = "docker.io"

"""

    for mirror_url in mirrors:
        config += f"""[[registry.mirror]]
location = "{mirror_url}"
insecure = true

"""

    with open("/etc/containers/registries.conf", "w") as f:
        f.write(config)


if __name__ == "__main__":
    generate_registries_conf()
