model_name_or_path: /model
model_revision: main
use_flash_attn: true
gradient_checkpointing: true
tokenizer_name: /model
use_slow_tokenizer: true
dataset_mixer:
  allenai/ultrafeedback_binarized_cleaned_train: 1.0
  ai2-adapt-dev/DaringAnteater-prefs-RM-filter: 1.0
  ai2-adapt-dev/WildChat-prefs-280824: 1.0
  ai2-adapt-dev/personahub_if_pref_data_v1: 1.0
  # ai2-adapt-dev/ultrafeedback-replication-p5: 1.0
  # ai2-adapt-dev/numina_math_gsm8k_prefs_balance_minerva_format_v2: 1.0
max_seq_length: 2048
preprocessing_num_workers: 16
per_device_train_batch_size: 1
gradient_accumulation_steps: 16 # designed for 8 GPUs, so batch size 128
learning_rate: 5.0e-7
lr_scheduler_type: linear
warmup_ratio: 0.1
weight_decay: 0.0
num_train_epochs: 1
output_dir: /output
with_tracking: true
report_to:
  - wandb
logging_steps: 1
use_lora: false
dpo_loss_type: dpo_norm
dpo_beta: 5
checkpointing_steps: 2000
