model_name_or_path: /model
model_revision: main
use_flash_attn: true
gradient_checkpointing: true
dataset_mixer:
  # Same UltraFeedback data from Tulu 2
  allenai/ultrafeedback_binarized_cleaned_train: 1.0
  # Custom conversion of daring anteater synthetic data into preferences
  ai2-adapt-dev/DaringAnteater-prefs-RM-filter: 1.0
  # Modifications of WildChat data to preferences with
  ai2-adapt-dev/WildChat-prefs-280824: 1.0
  # Custom IF Eval data with Llama 3.1 405B for chosen and Tulu 2 as rejected
  ai2-adapt-dev/Llama-3.1-if_taxonomy_tulu: 1.0
tokenizer_name: /model
use_slow_tokenizer: true
max_seq_length: 2048
preprocessing_num_workers: 16
per_device_train_batch_size: 1
gradient_accumulation_steps: 16 # designed for 8 GPUs, so batch size 128
learning_rate: 5.0e-7
lr_scheduler_type: linear
warmup_ratio: 0.1
weight_decay: 0.0
num_train_epochs: 1
output_dir: /output
with_tracking: true
report_to:
  - wandb
logging_steps: 1
use_lora: false
dpo_loss_type: dpo_norm
dpo_beta: 5
checkpointing_steps: 1000