name: GPU Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'open_instruct/grpo_fast.py'
      - 'open_instruct/vllm_utils3.py'
  merge_group:
  workflow_dispatch:

jobs:
  gpu-tests:
    name: Run GPU tests
    runs-on: GPU-Enabled-Runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.8.6"
      
      - name: Set up Python
        run: uv sync --frozen
      
      - name: Run GPU tests
        run: |
          uv run --frozen pytest -xvs tests/*_gpu.py open_instruct/*_gpu.py