name: GPU Tests

on:
  push:
    branches:
      - main
      - v*-release
  pull_request:
    branches:
      - main
  merge_group:
  workflow_dispatch:

jobs:
  gpu-tests:
    name: Run GPU tests
    runs-on: [self-hosted, gpu]  # Requires a GPU-enabled runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.8.6"
      
      - name: Set up Python environment
        run: uv sync
      
      - name: Verify CUDA availability
        run: |
          uv run python -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}'); print(f'CUDA devices: {torch.cuda.device_count()}')"
      
      - name: Run GPU tests
        run: |
          # Run all GPU test files
          uv run pytest -xvs tests/*_gpu.py open_instruct/*_gpu.py
        env:
          CUDA_VISIBLE_DEVICES: 0  # Use first GPU
          NCCL_CUMEM_ENABLE: 0