"""Generate CPU-safe MILES field references; --check fails on documentation drift."""

import argparse
import ast
import dataclasses
import hashlib
import html
import json
from pathlib import Path

from open_instruct.miles import config, run_spec

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs/miles"
GENERATED = (
    "<!-- Generated by python -m scripts.miles.generate_docs; edit reference-help.json or source definitions. -->\n"
)


def cell(value):
    return html.escape(str(value)).replace("|", "&#124;").replace("\n", " ")


def literal(value):
    return json.dumps(value, sort_keys=True)


def table(headers, rows):
    return (
        "\n".join(
            ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
            + ["| " + " | ".join(cell(x) for x in row) + " |" for row in rows]
        )
        + "\n"
    )


def source_constraints():
    """Include the explicit fixed-value/replacement checks without another registry."""
    tree = ast.parse((ROOT / "open_instruct/miles/config.py").read_text())
    constraints = {}
    for node in ast.walk(tree):
        if isinstance(node, ast.For) and isinstance(node.target, ast.Tuple):
            names = [getattr(x, "id", "") for x in node.target.elts]
            if names not in (["name", "expected"], ["name", "replacement"]):
                continue
            try:
                values = ast.literal_eval(node.iter.func.value)
            except (ValueError, AttributeError):
                continue
            constraints.update(
                {
                    key: f"Required value: {literal(value)}" if names[1] == "expected" else f"Rejected; use {value}"
                    for key, value in values.items()
                }
            )
    for name in (
        "train_backend",
        "custom_config_path",
        "config",
        "olmo_core_config",
        "data_source_path",
        "custom_async_data_buffer_path",
    ):
        constraints[name] = "Adapter-owned; cannot override"
    constraints.update(
        save_hf="Rejected; use output.export_hf or supported snapshot export",
        lora_rank="Must be nonpositive; LoRA is not implemented",
        max_weight_staleness="Must equal core.max_policy_lag",
    )
    constraints.update(
        micro_batch_size="Required value: 1; use Core sequence_packing for packed forwards",
        use_dynamic_batch_size="Required value: false",
        offload_train="Required value: false; resident Core trainer",
        qkv_format="thd with sequence_packing; bshd otherwise",
        check_weight_update_selector="Required value: all",
        ref_update_interval="Rejected; reference policy must be fixed",
        fully_async="Requires disaggregated resident engines and positive Core lag allowance",
        use_rollout_routing_replay="Requires use_miles_router; separate from Megatron replay",
    )
    for name in ("tensor_model_parallel_size", "pipeline_model_parallel_size", "context_parallel_size"):
        constraints[name] = "Required value: 1; this Core adapter does not implement trainer TP/PP/CP > 1"
    for name in ("use_critic", "multi_lora", "indep_dp", "use_opd", "use_routing_replay"):
        constraints[name] = "Required value: false; no Core implementation"
    return constraints


def render():
    help_data = json.loads((DOCS / "reference-help.json").read_text())
    native = json.loads((DOCS / "native-help.json").read_text())
    schema_path = ROOT / "open_instruct/miles/options.json"
    if native["schema_sha256"] != hashlib.sha256(schema_path.read_bytes()).hexdigest():
        raise ValueError("Native help provenance is stale; recapture against the updated parser snapshot")
    fields = dataclasses.fields(config.CoreConfig)
    if set(help_data["core"]) != {f.name for f in fields}:
        raise ValueError("Every CoreConfig field needs exactly one reviewed description")
    native_by_flags = {tuple(item["flags"]): item for item in native["options"]}
    schema = json.loads(schema_path.read_text())["options"]
    if set(native_by_flags) != {tuple(item["flags"]) for item in schema}:
        raise ValueError("Native help must cover every pinned parser action")
    undocumented = {item["dest"] for item in native["options"] if not item["help"]}
    if undocumented - set(help_data["native"]):
        raise ValueError(
            "Native options without source help need reviewed descriptions: "
            + str(sorted(undocumented - set(help_data["native"])))
        )
    result = {}
    text = (DOCS / "configuration-intro.md").read_text() + "\n" + GENERATED
    text += "\n## Workflow fields\n\n" + table(
        ["Field", "Type, default and behavior"], sorted(help_data["structured"].items())
    )
    text += "\n## Structured aliases\n\nNames below work in the organizational sections training, trainer, inference, optimizer, async, tracking and runtime unless stated otherwise. Use the semantically appropriate section shown in examples. These sections are not closed independent schemas: Core field names resolve to Core, other native names resolve to MILES.\n\n"
    text += table(["Alias", "Resolved target"], sorted(run_spec.FIELD_MAP.items()))
    text += "\n" + table(["Special control", "Behavior"], sorted(help_data["special"].items()))
    text += "\n## Core fields\n\nThese are dataclass defaults for raw CoreConfig. Structured compilation and example files can override them; null means unset.\n\n"
    text += table(
        ["Field", "Type", "CoreConfig default", "Meaning"],
        [("core." + f.name, str(f.type), literal(f.default), help_data["core"][f.name]) for f in fields],
    )
    text += "\n## Unsupported olmo-miles controls\n\n" + table(
        ["Field", "Replacement or limitation"], sorted(run_spec.UNSUPPORTED_FIELDS.items())
    )
    text += "\n## Example recipes\n\nGenerated from the actual structured TOMLs. These are recipe choices, not universal defaults or production qualification. GPU columns distinguish per-node trainers from total rollout GPUs.\n\n"
    rows = []
    for path in sorted((ROOT / "configs/miles/examples").glob("*.toml")):
        spec = run_spec.RunSpec.load(path)
        resolved = spec.compile()
        m = resolved.miles
        rows.append(
            (
                path.name,
                f"{m['actor_num_nodes']} × {m['actor_num_gpus_per_node']}",
                m["rollout_num_gpus"],
                m["colocate"],
                f"{m['rollout_batch_size']} × {m['n_samples_per_prompt']}",
                m["global_batch_size"],
                m["fully_async"],
                m["use_tis"],
                resolved.core.sequence_packing,
                m["num_rollout"],
            )
        )
    text += table(
        [
            "Example",
            "Trainer GPUs",
            "Rollout GPUs",
            "Colocated",
            "Prompts × responses",
            "Global batch",
            "Async",
            "TIS",
            "Packing",
            "Collections",
        ],
        rows,
    )
    result[DOCS / "configuration.md"] = text
    constraints = source_constraints()
    groups = {"native-training-options": [], "native-serving-options": []}
    for record in schema:
        name = record["dest"]
        detail = native_by_flags[tuple(record["flags"])]
        description = detail["help"] or help_data["native"][name]
        group = "native-serving-options" if name.startswith("sglang_") else "native-training-options"
        groups[group].append(
            (
                name,
                ", ".join(record["flags"]),
                record["type"] or record["kind"],
                literal(record.get("choices", [])) if "choices" in record else "—",
                literal(detail["default"]),
                constraints.get(name, "Parser option; subject to Core/model/runtime validation"),
                description,
            )
        )
    for name, rows in groups.items():
        result[DOCS / (name + ".md")] = (
            f"# {'SGLang' if 'serving' in name else 'MILES'} native option reference\n\n"
            + GENERATED
            + "\nUse these names under [miles]. Defaults below come from the pinned parser **before** structured, backend and model-dependent resolution. Some inherited options are inapplicable to Core; see the restrictions column and [run controls](run-controls.md). Parser acceptance is not qualification. Source help describes the upstream runtime, which may mention other backends.\n\n[Reference index and provenance](native-options.md).\n\n"
            + table(
                [
                    "TOML key",
                    "Native flags",
                    "Type/action",
                    "Choices",
                    "Parser default",
                    "Core restriction",
                    "Help (source or reviewed supplement)",
                ],
                rows,
            )
        )
    result[DOCS / "native-options.md"] = (
        "# Native MILES and SGLang options\n\n"
        + GENERATED
        + "\nFor normal runs start with the [configuration guide](configuration.md). Native flags use underscores under [miles]. This appendix includes every pinned parser action, including aliases and inherited backend options. It does not claim every parser option is implemented by the Core trainer.\n\n"
        + f"- [MILES options](native-training-options.md): {len(groups['native-training-options'])} actions.\n- [SGLang options](native-serving-options.md): {len(groups['native-serving-options'])} actions.\n\n"
        + "Help and raw defaults were captured from the actual parser in immutable Docker image `"
        + native["image"]
        + "`. The capture verified all action definitions against options.json; schema SHA-256: `"
        + native["schema_sha256"]
        + "`. This certifies the parser snapshot, not the image as a recommended training release.\n\nRefresh inside the matching pinned runtime, from a writable checkout:\n\n```bash\npython -m scripts.miles.capture_option_help --image IMMUTABLE_IMAGE_ID\npython -m scripts.miles.generate_docs\npython -m scripts.miles.generate_docs --check\n```\n\nThe capture refuses a parser-schema mismatch. If the runtime changed, regenerate and review options.json first using scripts/miles/snapshot_options.py. Source help is preserved; options without source help have reviewed supplements in reference-help.json. Conditional backend restrictions remain authoritative in config.py, validation.py and the installed runtime.\n"
    )
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in render().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(content)
    if stale:
        raise SystemExit("Generated docs are stale: " + ", ".join(stale))
    print("MILES reference checked" if args.check else "MILES reference generated")


if __name__ == "__main__":
    main()
