"""Generate MILES configuration and native-option references from their source schemas.
The documentation build uses these tables to keep defaults, descriptions and
constraints aligned with the checked-in configuration code and parser snapshot.
Generation runs without the GPU runtime so normal CPU documentation builds can
include the complete reference.
"""

import argparse
import dataclasses
import hashlib
import html
import json
from pathlib import Path

from open_instruct.miles.configuration import config, constraints, options, run_spec

ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs/miles"
GENERATED = (
    "<!-- Generated by python -m scripts.miles.generate_docs; edit reference-help.json or source definitions. -->\n"
)


def cell(value):
    return html.escape(str(value)).replace("|", "&#124;").replace("\n", " ")


def literal(value):
    return json.dumps(value, sort_keys=True)


def table(headers, rows):
    return (
        "\n".join(
            ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
            + ["| " + " | ".join(cell(x) for x in row) + " |" for row in rows]
        )
        + "\n"
    )


def source_constraints():
    """Describe the shared backend rules without inspecting validator source."""
    return constraints.native_descriptions()


def render(native_help=None):
    help_data = json.loads((DOCS / "reference-help.json").read_text())
    schema_path = ROOT / "open_instruct/miles/configuration/options.json"
    schema = options.load_schema(schema_path)["options"]
    fields = dataclasses.fields(config.CoreConfig)
    if set(help_data["core"]) != {f.name for f in fields}:
        raise ValueError("Every CoreConfig field needs exactly one reviewed description")
    native = json.loads(Path(native_help).read_text()) if native_help is not None else None
    native_by_flags = {}
    if native is not None:
        if native["schema_sha256"] != hashlib.sha256(schema_path.read_bytes()).hexdigest():
            raise ValueError("Native help provenance is stale; recapture against the updated parser snapshot")
        native_by_flags = {tuple(item["flags"]): item for item in native["options"]}
        if set(native_by_flags) != {tuple(item["flags"]) for item in schema}:
            raise ValueError("Native help must cover every pinned parser action")
        undocumented = {item["dest"] for item in native["options"] if not item["help"]}
        if undocumented - set(help_data["native"]):
            raise ValueError(
                "Native options without source help need reviewed descriptions: "
                + str(sorted(undocumented - set(help_data["native"])))
            )
    result = {}
    text = (DOCS / "configuration-intro.md").read_text() + "\n" + GENERATED
    text += "\n## Workflow fields\n\n" + table(
        ["Field", "Type, default and behavior"], sorted(help_data["structured"].items())
    )
    text += "\n## Structured aliases\n\nNames below work in the organizational sections training, trainer, inference, optimizer, async, tracking and runtime unless stated otherwise. Use the semantically appropriate section shown in examples. These sections are not closed independent schemas: Core field names resolve to Core, other native names resolve to MILES.\n\n"
    text += table(["Alias", "Resolved target"], sorted(run_spec.FIELD_MAP.items()))
    text += "\n" + table(["Special control", "Behavior"], sorted(help_data["special"].items()))
    text += "\n## Core fields\n\nThese are dataclass defaults for raw CoreConfig. Structured compilation and example files can override them; null means unset.\n\n"
    text += table(
        ["Field", "Type", "CoreConfig default", "Meaning"],
        [("core." + f.name, str(f.type), literal(f.default), help_data["core"][f.name]) for f in fields],
    )
    text += "\n## Unsupported Megatron-implementation controls\n\n" + table(
        ["Field", "Category", "Replacement or limitation"],
        [
            (name, rule.category.value, rule.message)
            for name, rule in sorted(constraints.UNSUPPORTED_RUN_FIELDS.items())
        ],
    )
    text += "\n## Example recipes\n\nGenerated from the actual structured TOMLs. These are starting recipes, not universal defaults; see [development defaults](development-defaults.md). GPU columns distinguish per-node trainers from total rollout GPUs.\n\n"
    allocations = []
    recipes = []
    for path in sorted((ROOT / "configs/miles/examples").glob("*.toml")):
        spec = run_spec.RunSpec.load(path)
        resolved = spec.compile()
        m = resolved.miles
        allocation = spec.plan()["allocation"]
        allocations.append(
            (
                path.name,
                f"{m['actor_num_nodes']} × {m['actor_num_gpus_per_node']}",
                m["rollout_num_gpus"],
                m["colocate"],
                allocation["judge_gpus"],
                allocation["replicas"],
                allocation["allocated_gpus"],
                allocation["unused_gpus"],
            )
        )
        recipes.append(
            (
                path.name,
                f"{m['rollout_batch_size']} × {m['n_samples_per_prompt']}",
                m["global_batch_size"],
                m["num_rollout"],
                resolved.core.publication_mode,
                m["fully_async"],
                resolved.core.max_policy_lag,
                m["use_tis"],
                resolved.core.sequence_packing,
            )
        )
    text += table(
        [
            "Example",
            "Trainer GPUs",
            "Rollout GPUs",
            "Colocated",
            "Judge GPUs",
            "Replicas",
            "Allocated GPUs",
            "Unused GPUs",
        ],
        allocations,
    )
    text += "\nAllocated GPUs include unused slots and managed judges, but exclude independent background evaluator jobs. Inspect `plan` for the evaluator schedule and per-job resources.\n\n"
    text += table(
        [
            "Example",
            "Prompts × responses",
            "Global batch",
            "Collections",
            "Publication",
            "Async",
            "Max policy lag (updates)",
            "TIS",
            "Packing",
        ],
        recipes,
    )
    result[DOCS / "configuration.md"] = text
    native_constraints = source_constraints()
    groups = {"native-training-options": [], "native-serving-options": []}
    for record in schema:
        name = record["dest"]
        detail = native_by_flags.get(tuple(record["flags"]))
        description = (detail["help"] if detail else None) or help_data["native"].get(name, "See pinned runtime help.")
        default = (
            literal(detail["default"])
            if detail
            else literal(record["default"])
            if "default" in record
            else "Not captured"
        )
        group = "native-serving-options" if name.startswith("sglang_") else "native-training-options"
        groups[group].append(
            (
                name,
                ", ".join(record["flags"]),
                record["type"] or record["kind"],
                literal(record.get("choices", [])) if "choices" in record else "—",
                default,
                native_constraints.get(name, "Parser option; subject to Core/model/runtime validation"),
                description,
            )
        )
    provenance = (
        "Full help and raw defaults were captured from the pinned parser in image `" + native["image"] + "`."
        if native
        else "This build uses the compact parser schema and reviewed integration descriptions. Full upstream help and value defaults were not captured; boolean defaults remain available from the schema."
    )
    for name, rows in groups.items():
        result[DOCS / (name + ".md")] = (
            f"# {'SGLang' if 'serving' in name else 'MILES'} native option reference\n\n"
            + GENERATED
            + "\nUse these names under [miles]. Defaults below come from the pinned parser **before** structured, backend and model-dependent resolution. Some inherited options are inapplicable to Core; see the restrictions column and [run controls](run-controls.md). Parser acceptance does not mean the Core trainer implements an option. Source help describes the upstream runtime, which may mention other backends.\n\n[Reference index and provenance](native-options.md).\n\n"
            + provenance
            + "\n\n"
            + table(
                [
                    "TOML key",
                    "Native flags",
                    "Type/action",
                    "Choices",
                    "Parser default",
                    "Core restriction",
                    "Help (source or reviewed supplement)",
                ],
                rows,
            )
        )
    result[DOCS / "native-options.md"] = (
        "# Native MILES and SGLang options\n\n"
        + GENERATED
        + "\nFor normal runs start with the [configuration guide](configuration.md). Native flags use underscores under [miles]. This appendix includes every pinned parser action, including aliases and inherited backend options. It does not claim every parser option is implemented by the Core trainer.\n\n"
        + f"- [MILES options](native-training-options.md): {len(groups['native-training-options'])} actions.\n- [SGLang options](native-serving-options.md): {len(groups['native-serving-options'])} actions.\n\n"
        + provenance
        + "\n\nThese pages are generated during the documentation build and are not tracked in Git. "
        + "The [architecture guide](architecture.md#documentation-checks) explains schema regeneration and optional native help capture. "
        + "The compact schema is tied to runtime.lock.json. Captured help must match its SHA-256 and every parser action. "
        + "Parser acceptance does not establish backend support; config.py, validation.py and the runtime enforce those restrictions.\n"
    )
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--native-help", type=Path, help="Optional help artifact captured in the pinned runtime")
    parser.add_argument(
        "--output-dir", type=Path, default=ROOT / "runs/miles-docs", help="Directory for generated Markdown"
    )
    args = parser.parse_args()
    rendered = render(args.native_help)
    if not args.check:
        args.output_dir.mkdir(parents=True, exist_ok=True)
        for path, content in rendered.items():
            (args.output_dir / path.name).write_text(content)
    print("MILES reference inputs checked" if args.check else f"MILES references generated in {args.output_dir}")


if __name__ == "__main__":
    main()
